export const USER = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",

    LOAD_REQUEST: "LOAD_REQUEST",
    LOAD_SUCCESS: "LOAD_SUCCESS",
    LOAD_FAILURE: "LOAD_FAILURE",

    UPDATE_REQUEST: "UPDATE_REQUEST",
    UPDATE_SUCCESS: "UPDATE_SUCCESS",
    UPDATE_FAILURE: "UPDATE_FAILURE",

    DELETE_REQUEST: "DELETE_REQUEST",
    DELETE_SUCCESS: "DELETE_SUCCESS",
    DELETE_FAILURE: "DELETE_FAILURE",

    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",
};

export const EVENT = {
    LOAD_REQUEST: " LOAD_REQUEST",
    LOAD_SUCCESS: " LOAD_SUCCESS",
    LOAD_FAILURE: " LOAD_FAILURE",

    LOAD_ALL_REQUEST: " LOAD_ALL_REQUEST",
    LOAD_ALL_SUCCESS: " LOAD_ALL_SUCCESS",
    LOAD_ALL_FAILURE: " LOAD_ALL_FAILURE",

    UPDATE_REQUEST: " UPDATE_REQUEST",
    UPDATE_SUCCESS: " UPDATE_SUCCESS",
    UPDATE_FAILURE: " UPDATE_FAILURE",

    DELETE_REQUEST: " DELETE_REQUEST",
    DELETE_SUCCESS: " DELETE_SUCCESS",
    DELETE_FAILURE: " DELETE_FAILURE",
};

export const CART = {
    ADD_REQUEST: " ADD_REQUEST",
    ADD_SUCCESS: " ADD_SUCCESS",
    ADD_FAILURE: " ADD_FAILURE",

    REMOVE_REQUEST: " REMOVE_REQUEST",
    REMOVE_SUCCESS: " REMVOE_SUCCESS",
    REMOVE_FAILURE: " REMOVE_FAILURE",

    BUY_REQUEST: " BUY_REQUEST",
    BUY_SUCCESS: " BUY_SUCCESS",
    BUY_FAILURE: " BUY_FAILURE",
};
