export const USER = {
    LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    LOGIN_FAILURE: "USER_LOGIN_FAILURE",

    LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",

    GET_REQUEST: "USER_GET_REQUEST",
    GET_SUCCESS: "USER_GET_SUCCESS",
    GET_FAILURE: "USER_GET_FAILURE",

    PATCH_REQUEST: "USER_PATCH_REQUEST",
    PATCH_SUCCESS: "USER_PATCH_SUCCESS",
    PATCH_FAILURE: "USER_PATCH_FAILURE",

    DELETE_REQUEST: "USER_DELETE_REQUEST",
    DELETE_SUCCESS: "USER_DELETE_SUCCESS",
    DELETE_FAILURE: "USER_DELETE_FAILURE",

    REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const EVENT = {
    GET_REQUEST: "EVENT_GET_REQUEST",
    GET_SUCCESS: "EVENT_GET_SUCCESS",
    GET_FAILURE: "EVENT_GET_FAILURE",

    GET_ALL_REQUEST: "EVENT_GET_ALL_REQUEST",
    GET_ALL_SUCCESS: "EVENT_GET_ALL_SUCCESS",
    GET_ALL_FAILURE: "EVENT_GET_ALL_FAILURE",

    PATCH_REQUEST: "EVENT_PATCH_REQUEST",
    PATCH_SUCCESS: "EVENT_PATCH_SUCCESS",
    PATCH_FAILURE: "EVENT_PATCH_FAILURE",

    DELETE_REQUEST: "EVENT_DELETE_REQUEST",
    DELETE_SUCCESS: "EVENT_DELETE_SUCCESS",
    DELETE_FAILURE: "EVENT_DELETE_FAILURE",
};

export const CART = {
    ADD_REQUEST: "CART_ADD_REQUEST",
    ADD_SUCCESS: "CART_ADD_SUCCESS",
    ADD_FAILURE: "CART_ADD_FAILURE",

    REMOVE_REQUEST: "CART_REMOVE_REQUEST",
    REMOVE_SUCCESS: "CART_REMOVE_SUCCESS",
    REMOVE_FAILURE: "CART_REMOVE_FAILURE",

    BUY_REQUEST: "CART_BUY_REQUEST",
    BUY_SUCCESS: "CART_BUY_SUCCESS",
    BUY_FAILURE: "CART_BUY_FAILURE",
};
