export const AREA_DEFAULTS = [{
    name: "1",
    defaultSeats: 5,
    defaultPrice: 250,
}, {
    name: "2",
    defaultSeats: 5,
    defaultPrice: 250,
}, {
    name: "3",
    defaultSeats: 5,
    defaultPrice: 300,
}, {
    name: "4",
    defaultSeats: 5,
    defaultPrice: 350,
}, {
    name: "5",
    defaultSeats: 5,
    defaultPrice: 300,
}, {
    name: "6",
    defaultSeats: 5,
    defaultPrice: 250,
}, {
    name: "7",
    defaultSeats: 5,
    defaultPrice: 250,
}, {
    name: "8",
    defaultSeats: 5,
    defaultPrice: 300,
}, {
    name: "9",
    defaultSeats: 5,
    defaultPrice: 325,
}, {
    name: "10",
    defaultSeats: 5,
    defaultPrice: 300,
}, {
    name: "11",
    defaultSeats: 50,
    defaultPrice: 50
}, {
    name: "12",
    defaultSeats: 25,
    defaultPrice: 50
}, {
    name: "13",
    defaultSeats: 10,
    defaultPrice: 50
}, {
    name: "14",
    defaultSeats: 25,
    defaultPrice: 30
}, {
    name: "15",
    defaultSeats: 10,
    defaultPrice: 20
}, {
    name: "16",
    defaultSeats: 10,
    defaultPrice: 20
}, {
    name: "17",
    defaultSeats: 60,
    defaultPrice: 20
}, {
    name: "18",
    defaultSeats: 75,
    defaultPrice: 30
}, {
    name: "19",
    defaultSeats: 50,
    defaultPrice: 150,
}, {
    name: "20",
    defaultSeats: 75,
    defaultPrice: 30
}, {
    name: "21",
    defaultSeats: 60,
    defaultPrice: 20
}, {
    name: "22",
    defaultSeats: 10,
    defaultPrice: 20
}, {
    name: "23",
    defaultSeats: 10,
    defaultPrice: 20
}, {
    name: "24",
    defaultSeats: 25,
    defaultPrice: 30
}, {
    name: "25",
    defaultSeats: 10,
    defaultPrice: 30
}, {
    name: "26",
    defaultSeats: 25,
    defaultPrice: 50
}, {
    name: "27",
    defaultSeats: 50,
    defaultPrice: 30
}, {
    name: "28",
    defaultSeats: 10,
    defaultPrice: 110,
}, {
    name: "29",
    defaultSeats: 20,
    defaultPrice: 130,
}, {
    name: "30",
    defaultSeats: 10,
    defaultPrice: 425,
}, {
    name: "31",
    defaultSeats: 20,
    defaultPrice: 130,
}, {
    name: "32",
    defaultSeats: 10,
    defaultPrice: 110,
}, {
    name: "33",
    defaultSeats: 10,
    defaultPrice: 110,
}, {
    name: "34",
    defaultSeats: 50,
    defaultPrice: 110,
}, {
    name: "35",
    defaultSeats: 70,
    defaultPrice: 125,
}, {
    name: "36",
    defaultSeats: 70,
    defaultPrice: 125,
}, {
    name: "37",
    defaultSeats: 50,
    defaultPrice: 110,
}, {
    name: "38",
    defaultSeats: 10,
    defaultPrice: 110,
}, {
    name: "39",
    defaultSeats: 10,
    defaultPrice: 110,
}, {
    name: "40",
    defaultSeats: 20,
    defaultPrice: 130,
}, {
    name: "41",
    defaultSeats: 10,
    defaultPrice: 425,
}, {
    name: "42",
    defaultSeats: 20,
    defaultPrice: 130,
}, {
    name: "43",
    defaultSeats: 25,
    defaultPrice: 30
}, {
    name: "44",
    defaultSeats: 50,
    defaultPrice: 100,
}, {
    name: "45",
    defaultSeats: 50,
    defaultPrice: 100,
}, {
    name: "46",
    defaultSeats: 25,
    defaultPrice: 30
}, {
    name: "47",
    defaultSeats: 20,
    defaultPrice: 20
}, {
    name: "48",
    defaultSeats: 20,
    defaultPrice: 95,
}, {
    name: "49",
    defaultSeats: 20,
    defaultPrice: 95,
}, {
    name: "50",
    defaultSeats: 20,
    defaultPrice: 20
}, {
    name: "A",
    defaultSeats: 30,
    defaultPrice: 20
}, {
    name: "B",
    defaultSeats: 20,
    defaultPrice: 20
}, {
    name: "C",
    defaultSeats: 30,
    defaultPrice: 20
}, {
    name: "D",
    defaultSeats: 20,
    defaultPrice: 20
}, {
    name: "Floor",
    defaultSeats: 100,
    defaultPrice: 20
}];
